repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: mixed-line-ending
-   repo: local
    hooks:
      - id: autopep8
        name: autopep8
        language: system
        entry: autopep8 --exit-code -iar feeds/ devrant/ forums/ reddit/ util/ ./main.py
        pass_filenames: false
      - id: pylint
        name: pylint
        language: system
        entry: pylint feeds/ devrant/ forums/ reddit/ util/ ./main.py
        pass_filenames: false
      - id: isort
        name: isort
        language: system
        entry: isort .
        pass_filenames: false
      - id: pycodestyle
        name: pycodestyle
        language: system
        entry: pycodestyle --show-source --show-pep8 feeds/ devrant/ forums/ reddit/ util/ ./main.py
        pass_filenames: false
