name: Linters

on:  
  push:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pycodestyle
    - name: Analysing the code with pylint
      run: |
        pylint blogs/ devrant/ forums/ reddit/ util/
    - name: Analysing the code with pycodestyle (pep-8)
      run: |
        pycodestyle --show-source --show-pep8 blogs/ devrant/ forums/ reddit/ util/